openapi: 3.0.0
info:
  title: 'User API'
  version: '0.1'
servers:
  -
    url: 'https://site.org'
paths:
  '/user/{id}':
    get:
      tags:
        - User
      operationId: 'Php\Fpm\UserInterface\Api\UserController::getAction'
      parameters:
        -
          name: id
          in: path
          description: 'Id for the user'
          schema:
            type: string
      responses:
        '200':
          description: 'User found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'
        '404':
          description: 'User not found'
          content:
            application/json:
              schema:
                properties:
                  status: { description: 'The response status', type: integer, format: int64 }
                  title: { description: 'The response not detailed message', type: string }
                type: object
  /user:
    post:
      tags:
        - User
      operationId: 'Php\Fpm\UserInterface\Api\UserController::postAction'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  description: 'User name'
                  type: string
              type: object
      responses:
        '200':
          description: 'User created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'
        default:
          description: 'An error occured'
          content:
            application/json:
              schema:
                properties:
                  status: { description: 'The response status', type: integer, format: int64 }
                  title: { description: 'The response not detailed message', type: string }
                type: object
components:
  schemas:
    UserResource:
      properties:
        id:
          description: 'The user id'
          type: string
        name:
          description: 'The user name'
          type: string
        self:
          description: 'The self url resource'
          type: string
      type: object
