openapi: 3.0.0
info:
  title: 'User API'
  version: '0.1'
paths:
  /user:
    get:
      operationId: 'Php\Fpm\UserInterface\Api\UserController::getAction'
      responses:
        '200':
          description: 'User resource'
